---
- name: sample book
  hosts: [containergroup]
  remote_user: sshuser
  become: true

  tasks:
  - name: create a test file
    file:
      path: "/ansible.txt"
      state: touch
    become: yes
  - name: create a file content
    copy:
      dest: "/test.txt"
      content: "Created by ansible!!!"